Repository cloudposse/terraform-aws-lambda-function, pull requests merged in 2023-05, with the labels that each got.

#37 Sync github
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto-release.yml
  .github/mergify.yml
  .github/renovate.json
  .github/workflows/auto-context.yml
  .github/workflows/auto-format.yml
  .github/workflows/auto-readme.yml
  .github/workflows/auto-release.yml
  .github/workflows/chatops.yml
  .github/workflows/feature-branch-chatops.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .github/workflows/release-published.yml
  .github/workflows/scheduled.yml
  .github/workflows/validate-codeowners.yml
  README.md
Labels: no-release

#31 Add ephemeral storage size option
  README.md
  docs/terraform.md
  examples/complete/fixtures.us-east-2.tfvars
  examples/complete/main.tf
  examples/complete/variables.tf
  main.tf
  variables.tf
Labels: minor

#39 fix: addresses issues with lambda cloudwatch log group
  main.tf
Labels: patch
